### ISSUE TITLE
can't see song title

### ISSUE THREAD

**Issue by romanarranz** [mpvillafranca/hearcloud#22]
i have uploaded a song just with title as meta information, but when i play it couldn't see his song title.

**Comment by mpvillafranca** [comment]
Something weird happened with that song file. Attach it here and I will test it to see what is happening.

**Comment by romanarranz** [comment]
<img width="1276" alt="captura de pantalla 2016-08-26 a las 12 45 58" src="https://cloud.githubusercontent.com/assets/11377513/18004060/e0c5cc7a-6b91-11e6-9c06-110bd44ec99c.png">

**Comment by mpvillafranca** [comment]
It should be working now! Something weird happens with that mp3 file and doesn't recognise the tags, don't know why... I will have a closer look to it during this days.
