### ISSUE TITLE
account settings

### ISSUE THREAD

**Issue by romanarranz** [mpvillafranca/hearcloud#23]
Profile and edit profile can be merged on account settings, because these links have the same resource.
When i try to edit my name i got a 500 error code.

**Comment by mpvillafranca** [comment]
"Account settings" is for the account stuff, like email, password change, etc and the "Profile" for the display options (picture, etc), it's just din't have time to implement it yet...

**Comment by mpvillafranca** [comment]
Will be fixed with #8
