### ISSUE TITLE
Playing a song in the song screen will open a new mp3 player window instead of using the hearcloud player in chrome

### ISSUE THREAD

**Issue by angrykoala** [mpvillafranca/hearcloud#27]
![2016-08-27 22_05_21-hearcloud](https://cloud.githubusercontent.com/assets/5960567/18030084/6ba72bd4-6ca2-11e6-9e52-6599c349ff9f.png)
_Clicking here_
![2016-08-27 22_05_43-hearcloud-mpvillafranca rhcloud com_static__media_angrykoala_30_seconds_to_mars_](https://cloud.githubusercontent.com/assets/5960567/18030085/6ba902a6-6ca2-11e6-9a76-6fe57d83013e.png)
_New window with chrome default player_

**Comment by mpvillafranca** [comment]
Yes, I know what you mean, it's just I didn't add the code that is lauching the hearcloud player there! Will be included in the next update :)
