### ISSUE TITLE
Download from song screen will fail

### ISSUE THREAD

**Issue by angrykoala** [mpvillafranca/hearcloud#28]
Trying to download from here, returns server Error 500. Error seems to happen when trying to download in m4a format from the list

![2016-08-27 22_09_45-hearcloud](https://cloud.githubusercontent.com/assets/5960567/18030105/0bbd033c-6ca3-11e6-96d9-85ddd0573186.png)
_Clicking Here_

**Comment by mpvillafranca** [comment]
Same thing here, didn't link to the new download url. Will be fixed asap too!
